[build]
  command = "npm run build:netlify"
  publish = "/"
  functions = ".netlify/functions"

[functions]
  external_node_modules = ["@vercel/functions", "@upstash/redis"]
  node_bundler = "esbuild"

[build.environment]
  NETLIFY = "true"
  NODE_VERSION = "22"

[[redirects]]
  from = "/*"
  to = ".netlify/functions/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"