[build]
  command = "npm run build:netlify"
  publish = "/"
  edge_functions = "netlify/edge-functions"
  functions = "netlify/functions"

[functions]
  external_node_modules = ["@vercel/functions", "@upstash/redis"]
  node_bundler = "esbuild"

[build.environment]
  NETLIFY = "true"
  NODE_VERSION = "22"

[[edge_functions]]
  function = "index"
  path = "/"

[[edge_functions]]
  function = "search"
  path = "/search"

[[edge_functions]]
  function = "poem"
  path = "/poem"

[[edge_functions]]
  function = "gemini"
  path = "/gemini"

[[edge_functions]]
  function = "weather"
  path = "/weather"

[[edge_functions]]
  function = "cors"
  path = "/cors"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"