[build]
  command = "npm run build:netlify"
  publish = "public"
  functions = ".netlify/functions"

[functions]
  external_node_modules = ["@vercel/edge-config", "@vercel/functions", "@vercel/kv"]
  node_bundler = "esbuild"

[build.environment]
  NETLIFY = "true"
  NODE_VERSION = "21"

[[redirects]]
  from = "/*"
  to = ".netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/"
  to = ".netlify/functions/index"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"