[build]
  command = "npm run build:netlify"
  publish = "/"
  edge_functions = "netlify/edge-functions"

[build.environment]
  NETLIFY = "true"
  NODE_VERSION = "22"
  NEXT_USE_NETLIFY_EDGE = "true"

[[edge_functions]]
  function = "index"
  path = "/"
  cache = "manual"

[[edge_functions]]
  function = "search"
  path = "/search"

[[edge_functions]]
  function = "poem"
  path = "/poem"
  cache = "manual"

[[edge_functions]]
  function = "gemini"
  path = "/gemini"

[[edge_functions]]
  function = "weather"
  path = "/weather"
  cache = "manual"

[[edge_functions]]
  function = "cors"
  path = "/cors"

[[edge_functions]]
  function = "rss"
  path = "/rss"
  cache = "manual"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"