name = "worker"
main = "worker.js"
compatibility_date = "2024-12-18"
compatibility_flags = ["nodejs_compat"]
no_bundle = false
# find_additional_modules = true
base_dir = "."

[build]
command = "node build.js && npm install"
cwd = "."
# watch_dir = ["api", "worker.js", "package.json"]

# [[rules]]
# type = "ESModule"
# globs = ["**/*.js", "**/node_modules/**/*.js"]
# module = true