name = "workers"
main = "worker.js"
compatibility_date = "2025-01-05"
compatibility_flags = ["nodejs_compat"]
no_bundle = true
find_additional_modules = true
base_dir = "."

[build]
# command = "npm install"
cwd = "."
# watch_dir = ["api", "worker.js", "package.json"]

[[rules]]
type = "ESModule"
globs = ["**/*.js"] # , "**/node_modules/**/*.js"]
module = true

[[kv_namespaces]]
binding = "KV"
id = "poem"
preview_id = "poem"